Repository glenn-m/promR, pull requests merged in 2019-04, with the labels that each got.

#20 Fix uninformative error messages
  R/format_metrics_data.R
  R/promR.R
  R/utils.R
  man/utilities.Rd
  tests/testthat/test-metrics-errors.R
  tests/testthat/test-response-check.R
Labels: bug

#25 Documentation: README
  README.Rmd
  README.md
Labels: documentation :book:

#27 adding in pkgdown docs
  docs/LICENSE-text.html
  docs/authors.html
  docs/docsearch.css
  docs/docsearch.js
  docs/index.html
  docs/link.svg
  docs/pkgdown.css
  docs/pkgdown.js
  docs/pkgdown.yml
  docs/reference/Prometheus-class.html
  docs/reference/Prometheus_metadataQuery.html
  docs/reference/Prometheus_query.html
  docs/reference/Prometheus_rangeQuery.html
  docs/reference/index.html
  docs/reference/metrics_current.html
  docs/reference/metrics_range.html
  docs/reference/promR-package.html
  docs/reference/utilities.html
Labels: enhancement :rocket:

#28 Fix metrics formatting functions
  R/format_metrics_data.R
  R/utils.R
  man/utilities.Rd
  tests/testthat/test-destring-values.R
  vignettes/.gitignore
Labels: enhancement :rocket:

#31 Metadata queries
  .Rbuildignore
  R/format_metrics_data.R
  R/promR.R
  README.Rmd
  README.md
  _pkgdown.yml
  docs/index.html
  docs/pkgdown.yml
  docs/reference/index.html
  docs/reference/utilities.html
  man/Prometheus_metadataQuery.Rd
  man/utilities.Rd
  tests/testthat/test-destring-values.R
  tests/testthat/test-metrics-format.R
  tests/testthat/test-response-check.R
Labels: enhancement :rocket:
